# Generated by Django 5.2.5 on 2025-08-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nameEnglish', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('subcategories', models.JSONField(blank=True, default=list)),
                ('seoTitle', models.CharField(blank=True, max_length=255)),
                ('seoDescription', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('articlesCount', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
                ('createdAt', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
