# Generated by Django 5.2.5 on 2025-08-21 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('subcategory', models.CharField(blank=True, max_length=255)),
                ('featuredImage', models.URLField(blank=True)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('isFeatured', models.BooleanField(default=False)),
                ('isHot', models.BooleanField(default=False)),
                ('isTrending', models.BooleanField(default=False)),
                ('isBreaking', models.BooleanField(default=False)),
                ('publishDate', models.DateField(default=django.utils.timezone.now)),
                ('publishTime', models.TimeField(default=django.utils.timezone.now)),
                ('seoTitle', models.CharField(blank=True, max_length=255)),
                ('seoDescription', models.TextField(blank=True)),
                ('seoKeywords', models.CharField(blank=True, max_length=255)),
                ('readTime', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.writer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.category')),
            ],
        ),
    ]
