# Generated by Django 5.2.5 on 2025-08-21 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_article_views_alter_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('news', 'News'), ('broadcast', 'Broadcast'), ('interview', 'Interview'), ('documentary', 'Documentary'), ('other', 'Other')], default='news', max_length=20)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.URLField(blank=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('facebook', 'Facebook'), ('custom', 'Custom')], default='custom', max_length=10)),
                ('platform_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('live', 'Live'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('live_start_time', models.DateTimeField(blank=True, null=True)),
                ('live_end_time', models.DateTimeField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.videocategory')),
            ],
        ),
    ]
